[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#155dfc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#0a0a0a"
font = "sans serif"
